url: "https://coumel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "psytccrennes" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.


sass:
    sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: "PSYCHOLOGUE - MELUSINE COURILLEAU"
description: "psychologue spécialisée dans la thérapie cognitive et comportementale à Rennes"
locale: "FR"
