url: "https://www.psy-tcc-rennes.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "PSYCHOLOGUE - PSYCHOTHERAPEUTE - TCC - RENNES - MELUSINE COURILLEAU" # the name of your site, e.g. ACME Corp.

sass:
    sass_dir: _sass

title: "PSYCHOLOGUE - MELUSINE COURILLEAU"
description: "psychologue spécialisée dans la thérapie cognitive et comportementale (TCC) à Rennes"
locale: "Fr"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
